export const REPORT_THEME = {
    textPrimary: "#111827",
    textSecondary: "#374151",
    textLight: "#6B7280",
    bgSecondary: "#F9FAFB",
    bgCard: "#FFFFFF",
    bgHighlight: "#EFF6FF",
    borderHighlight: "#BFDBFE",
    accent: "#3B82F6",
    accentDark: "#1E40AF",
    accentLight: "#DBEAFE",
    accentVeryLight: "#EFF6FF",
    success: "#10B981",
    error: "#EF4444",
    warning: "#F59E0B",
    white: "#FFFFFF",
    borderLight: "#E5E7EB",
    border: "#D1D5DB",
    bgHeader: "#3B82F6",
    bgZebra: "#EFF6FF",
};
